name: discussion

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  discussion:
    runs-on: self-hosted
    steps:
      - name: Syncing KaggleTracker repository
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Update disccusion
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          BOARD_ID: ${{ secrets.BOARD_ID }}
          COMMENTS_LIST_ID: ${{ secrets.COMMENTS_LIST_ID }}
          DONE_LIST_ID: ${{ secrets.DONE_LIST_ID }}
          TOPICS_LIST_ID: ${{ secrets.TOPICS_LIST_ID }}
        run: python run.py
      - name: Push discussion.csv
        run: |
          git add discussion.csv
          git commit -m "Update discussion.csv"
          git push origin main

