name: discussion

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dvc:
    runs-on: self-hosted
    steps:
      - name: Syncing KaggleTracker repository
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Update disccusion
        run: python run.py
